name: Mindbender Development Journal
description: development journal
meta_description: "Journal of important events related to the Mindbender pipeline."
markdown: kramdown
gems: [jekyll-paginate]
paginate: 20
baseurl: /journal
permalink: /p/:title/
author: Mindbender
defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
