name: Mindbender Development Journal
description: Mindbender Development Journal
meta_description: "Journal of important events related to the Mindbender pipeline."
markdown: kramdown
gems: [jekyll-paginate]
paginate: 20
baseurl: journal
permalink: /:year/:title/
defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
